name: Test for flJson

on:
  push:
    branches: [ "pref/parse" ]
  pull_request:
    branches: [ "pref/parse" ]

env:
  BUILD_TYPE: Release

jobs:
  flJson_GrammarTest:
    # 语法测试
    name: flJson_GrammarTest😆
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/bin -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_C_COMPILER=gcc -DBUILD_TEST=ON     # 使用BUILD_TEST=ON开启测试

    - name: Build       
      run: cmake --build ${{github.workspace}}/bin --target flJson_GrammarTest_Exe --config ${{env.BUILD_TYPE}}

    - name: Test Json Grammar
      working-directory: ${{github.workspace}}/bin
      run: ctest -R flJson_GrammarTest_Exe -V        # 需要展示详情


  flJson_SpeedTest:
    # 速度测试
    name: flJson_SpeedTest😆
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/bin -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_C_COMPILER=gcc -DBUILD_TEST=ON     # 使用BUILD_TEST=ON开启测试

    - name: Build       
      run: cmake --build ${{github.workspace}}/bin --target flJson_SpeedTest_Exe --config ${{env.BUILD_TYPE}}

    - name: Test Json Speed
      working-directory: ${{github.workspace}}/bin
      run: ctest -R flJson_SpeedTest_Exe -V        # 需要展示详情
